### ISSUE TITLE
"No configuration for this process state" for finished process

### ISSUE THREAD

**Issue by ghost** [bluesoft-rnd/aperte-workflow-core#102]
After the process ends you can see in "Recent tasks". However when clicked there appears a popup "No configuration for this process state". In modeler it is impossible to add configuration for "end" state.
IMO the user has to be able to view details of the process after it has ended.

**Comment by syiae** [comment]
same problem, any suggestions?

**Comment by kkolodziej** [comment]
Version 2.0 adds configuration for end state.
