### ISSUE TITLE
How to populate the data from user defind class to ComboBox

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#104]
Hi,

Can anybody suggest me how to achieve this.
My requirement is to populate the data from a userdefined class to a ComboBox.
(example: 
class country{
  public ArrayList city; // i want to populate the city into a ComboBox 
}
)
When i was designing a form in Aperte the options are like: AttributeClass & Bind.
Can explore the what is exact use of AttributeClass.( is my requirement is possible with this AttributeClass ? )

In Aperte "mule-flight-search" example he is populating the data from xml (Groovy code)  to ComboBox , like similarly i want to populate the data from a class to ComboBox.

Regards,
Veera

**Comment by tlipski** [comment]
Hi. You can:
- create simple java step (such as https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/log-step) which will operate on process attributes 
- provide your custom implementation of a combo list, such as UserData widgets - https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/userdata-widget - in such plugin you can hook any kind of logic that you require.

If you could be more specific about the logic that you need to implement in this class, I can try to point you in a more specific direction.

**Comment by tlipski** [comment]
AttributeClass - by default, processdata widget works with ProcessInstanceSimpleAttribute process attribute implementation. But, you can enhance ProcessInstanceAttribute class with your own data definition (such as CustomerData) and then, you can use ProcessData widget to access this class' attributes

**Comment by veeras** [comment]
Hi tlipski,

Can you provide sample working example on this issue (populate the data from java class to combobox). as we couldn't follow the Steps specified by you.

Thanks,
Veera
