### ISSUE TITLE
Drools with Aperte

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#105]
Hi tlipski,
thanks for your reply.
In my AperteWorkflow my seario will be like this:

I have totally 3 task : first one is userTaks & second one is DroolsStep & third one is userTask.
##  and the drl file in the DroolsStep is :

rule 'a'
when
    eval(true)
then
    System.out.println("HelloWorld");  
## end

When i submit the first userTask the above rule is firing and it is going to the my third usertask.
Here my requirement is to pass the data (like :username & password details which is entered the end user in first usertask)
to the rule (i want to check the username & password is right or wrong in the rule) and i want to pass the result  from rule to 
third usertask.

Thanks in Advance..

Regards,
Veera

**Comment by Bathakarai** [comment]
It is easy to pass the value from user task to rule task, and vise versa. You can use ProcessInstanceSimpleAttribute file for getting and setting the value using its bind name.

package org.aperteworkflow.drools.rules;

import java.util.Map;
import java.lang.*;
import pl.net.bluesoft.rnd.processtool.model.ProcessInstance;
import pl.net.bluesoft.rnd.processtool.model.ProcessInstanceSimpleAttribute;

global Map result;

rule 'Student creditable'

when

```
$pi : ProcessInstance()
$CategoryObj : ProcessInstanceSimpleAttribute(key=="category" ,value=="Student")
$amtObj :  ProcessInstanceSimpleAttribute(key=="price" ,eval(Integer.parseInt(value)<=500))
```

then
    result.put("value", "Creditable");
    System.out.println("----------------------------------------------------------------------------------");
    System.out.println("                Creditable customer         ");
    System.out.println("----------------------------------------------------------------------------------");
    ProcessInstanceSimpleAttribute obj=new ProcessInstanceSimpleAttribute();
    obj.setKey("credit");
        obj.setBpmVariableName("Creditable");
    obj.setValue("-------Creditable--------");
    $pi.addAttribute(obj);
end

In here, the key contains the BIND name and the value contains the user given value for that element. The "credit" is the user defined key name, use that key name to the next user task.
