### ISSUE TITLE
How to get plugins for : Creating-user-interfaces-with-step-editor

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#106]
Hi,
In the below link (tutorial) mentioned that following plugin bundles:

https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Creating-user-interfaces-with-step-editor

1)base-widgets
2)scripting
3)groovy-script-processor

I am not able to find above plugin bundles, Can you share a link to download (or) to get those plugin bundles 

Thanks,
Veera

**Comment by tlipski** [comment]
sure,

base-widgets - https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/base-widgets
scripting - https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/scripting
groovy-script-processor - https://github.com/zmalinowski/aperte-workflow-plugins/tree/master/groovy-script-processor (unmerged with the main fork yet)
