### ISSUE TITLE
Creating-user-interfaces-with-step-editor

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#107]
Hi tlipski,
Thanks for your quick reply..

In the below link (tutorial) mentioned that following plugin bundles:

https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Creating-user-interfaces-with-step-editor

1)base-widgets
2)scripting
3)groovy-script-processor

When i deploy above three bundles (base-widgets-1.0.jar 
                                                                 scripting.jar 
                                                                  groovy-script-processor-1.0-SNAPSHOT.jar )
in osgi-plugins (tomcat) . 

But i am not able to see the options like :
1) Run Script on Change 
2) Id 
3) Visible

So can u help me on this..

Thanks,
Veera

**Comment by tlipski** [comment]
scripting support is a feature for 1.1. It is somewhat ommited in the tutorial, so Zbigniew please update tutorial information

**Comment by zmalinowski** [comment]
Ok, now it's mentioned in Assumptions. I'm closing this issue.

**Comment by murthy516** [comment]
Hi zmalinowski,

As per documents specification,I builded base-widgets file from github master and placed in aperte1.0 version.I'm able to see all options.But,I'm unable to run,getting error as scripting error.Does any other thing I need to build from github?
