### ISSUE TITLE
Getting value from one process to another

### ISSUE THREAD

**Issue by Bathakarai** [bluesoft-rnd/aperte-workflow-core#108]
Hi,
       I have 2 processes. When I invoke the first process i give some value in the text box. After completion of the first process i invoke the second one. Here, i use one text box with the same bind name. But the value is not taken from the first process. Please suggest me how to do that.

Thanks in advanced.

**Comment by tlipski** [comment]
Each process instance has its own set of attributes. So, to persist information across process instances, you have to store them elsewhere - e.g. use mule to update/query database.
