### ISSUE TITLE
Creating-user-interfaces-with-step-editor

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#110]
Hi tlipski/ zmalinowski,

i downloaded the latest code form github.
 while doing "Creating-user-interfaces-with-step-editor " at  6th step which u mentioned in tutorial
(6.Click on Widget preview tab - you should see something like on the picture:)
 i got the "script error".
and i place the 3 bundles in osgi folder in aperte  which u mentioned in tutorial .

How to overcome this.

Thanks,
 Veera

**Comment by murthy516** [comment]
As per documents specification by zmalinowski,I builded base-widgets file from github master and placed in aperte1.0 version.I'm able to see all options.But,I'm unable to run,getting error as scripting error.Does any other thing I need to build from github?

**Comment by tlipski** [comment]
1.1 will be out tomorrow officially with scripting support
