### ISSUE TITLE
Unable to display values fetched from Database in table format

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#111]
Hi Aperte Guys,

I've UserTask and I also have a MuleStep.In MuleStep,I've written groovy script to fetch ProductDetails(Mobile,DTH,BroadBand)from Database.It is successfully done.But,I need to display these three values in a table format or normal labels.But,in Usertasks,ComboList,RadioButton only available to retrieve more values.I should have Label,which will take this list and displays in console like
Mobile
Broadband
DTH..

How I can do this..Suggest me pls..Is it possible?

**Comment by tlipski** [comment]
at this moment, tabular display of data could be received by implementing custom vaadin widget (tutorial on the way)
