### ISSUE TITLE
Does Aperte Supports Web Service Invoking

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#112]
Hi,

I successfully able to invoke   WebService using Mule.But,I'm unable to invoke that WebService in Aperte.I specified Mule flow URL in MuleStep of APerte.But,WebService is not invoking.Does Aperte supports invoking a WebService?.Please suggest me guys

**Comment by tlipski** [comment]
The other way to invoke web services (Mule ESB should work fine anyway) from Aperte Workflow would be to use some kind of wsdl2java task (e.g. provided by your IDE or maven) and build custom ProcessToolStep implementation
