### ISSUE TITLE
Starting Process from other Portlet.

### ISSUE THREAD

**Issue by chethu24** [bluesoft-rnd/aperte-workflow-core#113]
Hi All,

How can i Start the Process from Custom Portlet (i,e using Portlet outside Aperte Workflow Activities Portlet). just by inputting bpmdefintionkey or processname ("FavoriteQuoteProcess") or any other way. 

I've Imported the aperteworkflow source code to eclipse. From here can anyone Please tell how can i accomplish the above Task.

Regards,
Chethan

**Comment by tlipski** [comment]
Such API is not available yet. At this moment, you can replace/join base-gui/jbpm-gui artifacts on maven level with your implementation. But it will have different classloader/osgi plugins than aperteworkflow.war so it won't be easy to use them together.

**Comment by chethu24** [comment]
Hi tlipski,

Thanks for Reply.

I want know how to start the process without human interventions. like, some other system will trigger the process. And that should Start the process in our Aperte Process Engine.

Regards,
Chethan

**Comment by tlipski** [comment]
You can write a plugin, that will provide an interface to do that (not portlet though). Please check email capture plugin, which starts processes when a certain email arrives to a mailbox (and does much more)

https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/email-capture

**Comment by chethu24** [comment]
Hi tlipski,

Thanks for Reply.

Is Wiki for Email capture , https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Email-Capture-plugin
is enough to make it working or anything else i've to do. I already have email capture plugin in my Eclipse Workspace & configured with db. Can i get Sample configuration & Sample template.

Regards,
Chethan
