### ISSUE TITLE
Aperte ParallelGateway

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#114]
Hi,

When i Designing the flow in Aperte "ParallelGateway" , while saving it is showing error like:

Object named 'ParallelGateway' is not supported.

I didn't find any tutorial on "ParallelGateway" ,Can u provide the tutorial link to work on ParallelGateway.

Thanks,
Veera

**Comment by tlipski** [comment]
Parallel gateways will be supported in the next version - we are currently working on their support.
