### ISSUE TITLE
Aperte next version date

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#118]
Hi tlipski,

 I am sorry for disturbing you every time. According to our previous posts in this forum, i got the reply  that
  most of the features will going to released in the next version of Aperte. So if u don't mind can you provide the exact date for
  that , So that we can decide to proceed with Aperte or not.

 Please give me some advice on this.

Thanks,
Veera

**Comment by tlipski** [comment]
Aperte 1.1 will is ending its internal testing and will be available pretty soon (this or next week). This version will bring Activiti 5.8 integration and scripting support. 

Aperte 1.2, which will merge lots of features, including parallel execution or enhanced dictionaries should be available in April too.
