### ISSUE TITLE
Can Process be exposed as Service in Aperte

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#119]
Can I expose a Process as a Service in Aperte.Is it possible to invoke that service in mulestep of another process.

Thanks

**Comment by tlipski** [comment]
what do you mean by that? What do you want to achieve?

**Comment by murthy516** [comment]
Hi Tom,

In other editors like Activity,we can convert the BPMN Process as WebService(Generate Web Service).My Idea is When I convert process as webservice,I can invoke that service in one of the user task of another process,so that subprocess concept can be achieved.Does it possible converting BPMN Process into WebService.

Thanks
Krrish

**Comment by tlipski** [comment]
all right. You can expose Aperte Workflow API using Web Services quite easily using Mule plugin - I will try to provide a sample when I have a moment (it will an awesome feature too!)

**Comment by tlipski** [comment]
I have commited SOAP API for Aperte Workflow to merge_A branch
