### ISSUE TITLE
My ComboList is not getting Updated or refreshed

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#120]
Hi,

I have ComboList in UserTask where I fetched the values from a database.I started the process,and the values are being  displaying in that List.But,at that time If I added new record in database,it is not getting reflected in the list in console.

Even I refreshed the page,it is not getting new record from DB.Ofcourse,If I start the process again,it is getting new record.But,I needed it without starting new instance.Just by refreshing the page I need that new record.Is it possible?If so,can you suggest me how

**Comment by tlipski** [comment]
this comes directly from Vaadin mechanics, where app state is persisted across page reloads. 

To update such component, you can add refresh icon/button, which will update the list (just like it is done with task queues list in the Aperte Workflow Activities portlet). To refresh it automatically, you would need to spawn a background checker thread, which is not a desired approach. You can also create some kind of search mechanism/control with a dynamic Container (https://vaadin.com/book/-/page/datamodel.container.html) which will react directly to the users' input and therefore would show most current database state.
