### ISSUE TITLE
Timer in Aperte

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#124]
Hi

Is the Timer is implemented in Aperte or not.

my requirement is like this:
i have 3 user tasks, for each user task i am going to assing a time (2 min) , so u should complete that particular usertask with in 2 min otherwise the process is going to end (or) we have to show error.

Thanks,
Veera

**Comment by tlipski** [comment]
Aperte Modeler does not support this feature, but it should be provided in the near feature. When using jBPM, you might also use timer feature provided directly by jPDL (but you won't be able to use modeler then).

Also please have a look at the deadlines functionality in Aperte Workflow it might just fit your needs.
