### ISSUE TITLE
Scripts in Aperte

### ISSUE THREAD

**Issue by Bathakarai** [bluesoft-rnd/aperte-workflow-core#125]
Hi,
     In my aperte workflow I am always using groovy script. It is possible to use some other scripting (like java script) in aperte? If it so give some example for that..

Thanks in advanced...

**Comment by tlipski** [comment]
yeah, you just have to provide your scripting provider. Two sample providers are drools and groovy script processors (just merged them here: https://github.com/bluesoft-rnd/aperte-workflow-plugins)
