### ISSUE TITLE
Email Integration in Aperte Workflow

### ISSUE THREAD

**Issue by chethu24** [bluesoft-rnd/aperte-workflow-core#126]
Hi All,

I want to know how to use Email-Capture & bpm-notification Plugins when a Process Starts or state of the process changes. Please anybody provide me Step by Step Instruction with some Examples.

Thanks & Regards,
Chethan

**Comment by tlipski** [comment]
bpm-notification is a good general direction to go

**Comment by tlipski** [comment]
there is also some documentation here (not tutorial) https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/BPM-Notifications-plugin and the plugin itself is quite simple.

**Comment by chethu24** [comment]
when does the email notification is fired in the process by bpm-notification.
And how to notify after any Task in the Process is submitted.

**Comment by tlipski** [comment]
you should provided appropriate configuration to the mechanism, which will fire notification upon process entering certain states

**Comment by chethu24** [comment]
Where is the configuration to be provided?? Please let me know.

**Comment by chethu24** [comment]
In Table pt_ext_bpm_notify_config
Fields:
  processtyperegex =.*
  stateregex=.*

Is this is a place where i can change configurations.
What should i specify here to Notify upon process entering certain states.
