### ISSUE TITLE
BPM Notification

### ISSUE THREAD

**Issue by chethu24** [bluesoft-rnd/aperte-workflow-core#127]
I'm facing the below exception while using bpm-notification plugins. 

SEVERE: Access to default session denied
java.lang.SecurityException: Access to default session denied

java.lang.ClassCastException: pl.net.bluesoft.rnd.pt.ext.bpmnotifications.model.BpmNotificationTemplate cannot be cast to pl.net.bluesoft.rnd.pt.ext.bpmnotifications.model.BpmNotificationTemplate

Please anybody help me out.

Thanks in Advance,
Chethan

**Comment by tlipski** [comment]
we'll look into that

**Comment by chethu24** [comment]
In mail.properties file. of bpm-notification
Is below config is rite?

mail.smtp.host=smtp.gmail.com
mail.smtp.socketFactory.port=995
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.smtp.auth=true
mail.smtp.port=995
mail.smtp.user=chethan.dhananjaya@treetechnologies.net
mail.smtp.password=********

**Comment by tlipski** [comment]
it looks so, anyway I don't think that the config is issue here since we are getting ClassCastExceptions

**Comment by chethu24** [comment]
Im able send the notification  when i replaced code in bpm-notification plugin. i,e in BpmNotificationEngine Class i replaced

javax.mail.Session mailSession = javax.mail.Session.getDefaultInstance(mailProperties,
new javax.mail.Authenticator() {
protected PasswordAuthentication getPasswordAuthentication() {
mailProperties.getProperty("mail.smtp.password"));
 }});

with

Properties props = new Properties();
props.put("mail.smtp.user", "chethu24@gmail.com");
props.put("mail.smtp.host", "smtp.gmail.com");
props.put("mail.smtp.port", "465");
props.put("mail.smtp.starttls.enable","true");
props.put("mail.smtp.debug", "true");
props.put("mail.smtp.auth", "true");
props.put("mail.smtp.socketFactory.port", "465");
props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
props.put("mail.smtp.socketFactory.fallback", "false");
SMTPAuthenticator auth = new SMTPAuthenticator();
javax.mail.Session mailSession = javax.mail.Session.getInstance(props, auth);

and used SMTPAuthenticator class.

class SMTPAuthenticator extends Authenticator
{
    public PasswordAuthentication getPasswordAuthentication()
    {
        return new PasswordAuthentication("chethu24@gmail.com", " *****_password**_\* ");
    }
}

**Comment by chethu24** [comment]
Now BPM notification is working fine but i want know How can i send the Details entered in a Human Task.

Now Its notifying like:

---

Process SOM.60121 experienced a state change to Address Details, triggered by user test.

This is also a valid Freemarker template, one can use most of the language features

---

But i want..

---

Process SOM.60121 experienced a state change to Address Details, triggered by user test.

Address Details:
1600 Amphitheatre Parkway, Mountain View, California, 94043

---

How i can do this. Should i use Regular expression. & bind name.?

---

What all possible regex we can have like below:

${process.internalId}
${process.state}
${user.login}

---

Regards,
Chethan

**Comment by tlipski** [comment]
the bpm notification engine uses freemarker (http://freemarker.org/) templating engine. In the template you can use ProcessInstance object and therefore access all process attributes entered during the previous process steps.

**Comment by tlipski** [comment]
so, to access address data you would do sth like this: ${process.getSimpleAttributeValue("address")} - but make note that I am writing this w/o testing if it works, so the syntax may differ a little
