### ISSUE TITLE
java.lang.String cannot be cast to pl.net.bluesoft.rnd.processtool.model.ProcessInstanceAttribute

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#130]
Hi ,

I am getting the folowing exception while passing data from mule to aperte

SEVERE: java.lang.String cannot be cast to pl.net.bluesoft.rnd.processtool.model.ProcessInstanceAttribute
java.lang.ClassCastException: java.lang.String cannot be cast to pl.net.bluesoft.rnd.processtool.model.ProcessInstanceAttribu
te
## my mule code is:

```
   def data = "" ;
def pp = ""; 
pp = String.valueOf(data); // here the data  is : [{http://org/in/treetech/bss/ProductAvailability/ProductSearch}offerName[attributes={}; value=[3000 Texts]]]
payload.addDictionaryAttributeItem("availableOffers", pp, pp); 

}
```

Suggest me where i did wrong..

**Comment by tlipski** [comment]
looks like somewhere in your mule service you have changed payload to string. The sample Mule service is available here: https://github.com/bluesoft-rnd/aperte-workflow-core/blob/master/samples/mule-flightsearch-sample/src/main/resources/mule-flightsearch-sample.xml
