### ISSUE TITLE
Showing Process Map Diagram

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#134]
Hi,

There is Process Map for every active running process instance in AperteWorkflowInstances Portlet..My requirement is I need to display that ProcessMap diagram in the form of UserTask itself by providing a link or any other means.

So,to do that I need to know where that Process Map(diagram) is storing?In the DB?If so,can you suggest me how and where the Process Map is being stored,and also the Classes in source code  from which ProcessMap is being displayed..

Thanks
Krishna

**Comment by tlipski** [comment]
hi,

you can access process diagram by calling ProcessToolBpmSession#byte[] getProcessMapImage(ProcessInstance pi);

you can also access process execution history in a form of graph nodes (for visualization e.g. using SVG):

```
ProcessToolBpmSession#List<GraphElement> getProcessHistory(ProcessInstance pi);
```

an example of that is provided inside of org.aperteworkflow.portlets.ProcessInstanceManagerApplicationPortlet class, but take note, that to display SVG, custom portlet request handler is provided (and this portlet is available to administrators only). 

So, to display SVG you should provide some kind of external servlet/portlet which will render it (and serve process image). I've tried embedding SVG directly in Vaadin, but to no result (not saying that it can't be done either).
