### ISSUE TITLE
what is vm ? in mule-flight-search.xml

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#136]
Hi,

 <vm:inbound-endpoint address="vm://flightValidation"/> 

in the above line what "vm" will represent, Is it possible to change that name(vm) [ Is it possible to give our own name]
If it possible means where i have to modifications ?

Thanks,
Veera

**Comment by tlipski** [comment]
hi

vm is a Mule ESB VM (Virtual Machine) transport. It provides endpoints internally inside of Java VM. Other transports include http, jms, etc. - but vm:// is simplest. 

to use another endpoint, you can switch vm://flightSearch to for example vm://customerSearch

the endpoint address is referenced on the process map in a configuration of a mule step
