### ISSUE TITLE
How to close Process Map Diagram?

### ISSUE THREAD

**Issue by Bathakarai** [bluesoft-rnd/aperte-workflow-core#140]
Hi,
       In my Aperte workflow when I click the start button means i can able to display the Process Map Diagram by using "application.getMainWindow().addWindow(w1);"  function. While I navigate from one user task to another at that time it shows another Process Map Diagram (for displays current user state) . Mean while the first Process Map Diagram also still display. Now i need to delete the first Process Map Diagram after that display the second Process Map Diagram. Please suggest me how to do it...

---Thanks & Regards,
  Bathakarithangam

**Comment by tlipski** [comment]
Have you tried invoking application.getMainWindow().removeWindow(w1); ?
