### ISSUE TITLE
Where Aperte is fetching Pending Tasks and realted Users

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#142]
Hi,

I've a Process with two user tasks.I've two liferay Users Krisv,Jon.I created Process queues with those Liferay User names and I used them in Candidate groups.So,whenever krisv completes task1,Jon is getting Task2.

But,I need to have customizable look where whenever Jon Logs in,he needs to see What is the Particular task is Pending for him.(He should not click on Claim Task,it should display automatically in a portlet).Here,I need to write my Custom Code to achieve this.

But,my doubt is how Aperte is maintaining the pending,progressing,completing tasks related to particular users.Is it In DB,?If so,where these all data is being persisting.Please suggest me

**Comment by tlipski** [comment]
responded here: http://www.aperteworkflow.org/pl/forum/-/message_boards/view_message/13942
