### ISSUE TITLE
Mule Step

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#143]
Hi

In aperte we are moving from usertask to mulestep thorugh "vm://anyname"
Is this possible to call that "vm://anyname" from outside(not from usertask) like:broswser or java or another portlet ect..

Thanks,
Veera

**Comment by tlipski** [comment]
yeah, you can use any endpoint supported by Mule, e.g. http://localhost:9011/test or jms://somethingsomething

but... you have to keep in mind, that Mule Step when invoked, provides whole process data. so it might not be feasible to use it outside the JVM
