### ISSUE TITLE
Change the Aperte Workflow Activities Portlet size?

### ISSUE THREAD

**Issue by Bathakarai** [bluesoft-rnd/aperte-workflow-core#147]
Hi Tlipski,
                Thank you for your previous responses. I 've a doubt regarding "Aperte Workflow Activities" Portlet. I need to set the size to aperte workflow activities portlet and also want to set the portlet minimum size(Could not decrease beyond that) . I tried to  set the height (using "getMainWindow().setHeight("500px");") in ActivityPortletApplication class.But it not changed. Please tell me where to set the height?

Thanks in advanced
Bathakaraithangam

**Comment by pstepaniak** [comment]
Sorry for the late response.
The easiest way to modify the looks of the Aperte Workflow Activities Portlet is to use the 'Look and Feel' option that Liferay provides. 
Click on the tool icon on the 'Aperte Workflow Activities' portlet and choose the 'Look and Feel' option. Then choose the 'Advanced styling' tab. Here you can provide a custom css just for this portlet. Choose the 'Add css just for this portlet' link and provide in the 'Enter your custom css' window the constraints you want. 
For example, this sets the height of the 'Aperte Workflow Activities' portlet to 1600px:
#portlet_ProcessToolActivities_WAR_aperteworkflow{
    height: 1600px;
}

If you have any other questions about Aperte Workflow Usage, please post them to our forum:
http://www.aperteworkflow.org/forum/-/message_boards?_19_tabs1=categories&_19_mbCategoryId=13775
