### ISSUE TITLE
[Modeler] No default language for process messages

### ISSUE THREAD

**Issue by pnagrodkiewicz** [bluesoft-rnd/aperte-workflow-core#151]
One may define process messages in any language, but there is no such option as default value for the properties (or default language). For example, if you define Polish and English messages both work well if used in GUI definitions as long user is using any of these two languages, but if he or she switch to some other language (eg. German) in GUI will appear only property name instead of some human readable message.

Workaround: download process definition bundle and add manually file messages.properties - it will be used as default values (it may be copy of one of existing files, eg. messages_en_US.properties).

**Comment by kkolodziej** [comment]
Fixed in https://github.com/bluesoft-rnd/aperte-workflow-core/commit/8ed40a16caabb5106c77f0a017fe97ab65783a75 and https://github.com/bluesoft-rnd/signavio-core-mirror/commit/a0236ca293d7d614d5665acaf6136f80c9e7d2b8
