### ISSUE TITLE
[Modeler] Liferay freezes when wrong name of task.

### ISSUE THREAD

**Issue by kkolodziej** [bluesoft-rnd/aperte-workflow-core#160]
Whole Aperte Workflow freezes until restarted, when the new line(Enter) is put as the first sign in Task name.

**Comment by kkolodziej** [comment]
This problem happens only on Chrome. Probably a signavio bug.

**Comment by mmroczkowski** [comment]
Not reproductible on latest Chrome.

Edit: One new line is not sufficient to reproduce. Multiple new lines cause freeze.

**Comment by kkolodziej** [comment]
Repaired in https://github.com/mmroczkowski/signavio-core-mirror/commit/041c2c66ba49fb2a6b29ca9a9648663dcbbd9f2e
