### ISSUE TITLE
I18n in Aperte Workflow.

### ISSUE THREAD

**Issue by kkolodziej** [bluesoft-rnd/aperte-workflow-core#192]
After changing language in Liferay, aperte does nothing!  Logout/login is required for the change to take effect. Going to next step in process, changes the process language but not in the whole Aperte Workflow.

**Comment by mmroczkowski** [comment]
Confirmed in apw 2,0, language changes in aperte require relog.

**Comment by pjolszewski** [comment]
aperte ui & widgets require some reworking to handle changed language. dictionaries may cause serious headahe due to theirs current model

**Comment by mmroczkowski** [comment]
Most aperte messages are statically resolved on portlet construction. Dynamic language change require loads of additional implementation in all existing aperte components.
Current behavior will not be changed, user will get notification about relog requirement on language change.
