### ISSUE TITLE
File Upload Widget Problem

### ISSUE THREAD

**Issue by kkolodziej** [bluesoft-rnd/aperte-workflow-core#209]
Apparently the "File Upload Widget" is not working at all. It is possible to add file but its look like, it is not stored. After steeping to next human task the file list is empty. Even more when form is save the file list  disappears. If that is not enought it is very hard to download anything, becouse web browser always try to open file rather than download it.

**Comment by mmroczkowski** [comment]
Added absent save/load implementation for upload widget, corrected of many bugs on the way. Widget should be fully functional now.

**Comment by kkolodziej** [comment]
The file upload Widget was not properly tested, it fails on script execution.
