### ISSUE TITLE
Aperte 2.0 MySQL problem

### ISSUE THREAD

**Issue by mcolucci82** [bluesoft-rnd/aperte-workflow-core#235]
Hello,
I installed the 2.0 version of aperteworkflow (workflow-jbpm-2.0-liferay6.0.6-demo) and I configured it with MySQL DB but I find an error when I insert the portlet Activities in liferay. The error in question is "com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'aperteworkflow.jbpm4_hist_actinst' does not exist."
Could you give me any advice how to solve it?

Thanks
Maurizio

Server dates:
Centos 6
MySql 5.5
JAVA 1.6.0.35

**Comment by kkolodziej** [comment]
Hi,
Unfortunately we cannot repeat this error, we installed mysql DB and everything works fine. How did you configure, db? 
For some creating tables took some time (about 5-10 minutes). Maybe you tried to add activity before jbpm4_hist_actinst was created. could you confirm that by looking into your db?
Please, maybe try again, and wait until installed osgi plugins will be shown in logs.

Regards
Kamil Kołodziej

**Comment by mcolucci82** [comment]
Hello,
We have reinstalled everything again, but we always have the same problem. In the created DB, when you first open AperteWorkflow, the  jbpm4_hist_actinst table is present and in the log there are the prints that indicate the successful installation of the osgi-plugins.
At the moment, we install the PostgreSQL where everything is working properly.

We want inform you that our MySQL configuration was standard, we have not modified any parameter after installation (MySQL version 5.5.31 on Centos 6.4).

Thanks

Best regards

**Comment by kkolodziej** [comment]
I open thread with your problem on our community forum, maybe someone else had similar problems. I realized that i was testing it on 5.6, maybe using 5.5.31 will repeat error, I will try, and let you know as soon as I finish it.

**Comment by kkolodziej** [comment]
Does not apply version 3.0
