### ISSUE TITLE
AperteModeler not working

### ISSUE THREAD

**Issue by lauritomarcos** [bluesoft-rnd/aperte-workflow-core#237]
I've installed aperteworkflow and apertemodeler in Liferay Tomcat bundle but when i go to http://localhost/apertemodeler and login, it shows a label with the message: "The application could not be loaded. Please double check your internet connection and reload the page" with a Reload button.
any help?

**Comment by kkolodziej** [comment]
It is not a bug, moved to aperte Forum: http://www.aperteworkflow.org/forum/-/message_boards/view_message/16886
