### ISSUE TITLE
Automatic step transition allows button type attribute

### ISSUE THREAD

**Issue by kdowbecki** [bluesoft-rnd/aperte-workflow-core#27]
Aperte Modeler allows to select button type attribute (and so ProcessToolActionButton implementation) on transitions outgoing from the automatic step. 

This should only be possible on human resource step.

**Comment by kdowbecki** [comment]
Also observed on Start / End events and Gateways .

**Comment by kdowbecki** [comment]
Displaying of Aperte Action Editor was fixed in 
https://github.com/kdowbecki/signavio-core-mirror/commit/e77ce74ef3ae458199706a02b839ffaf2316ab9b. 

Still needs some work in Attributes Panel as well as clear strategy on what should happen when transition source is changed from user step to something different.

**Comment by tlipski** [comment]
attributes should be readonly and if we eventually will come up with better approach - another issue will be filled.
