### ISSUE TITLE
cleanup maven artifacts for incoming 1.0.0

### ISSUE THREAD

**Issue by tlipski** [bluesoft-rnd/aperte-workflow-core#42]

**Comment by kdowbecki** [comment]
Work started.

**Comment by kdowbecki** [comment]
Most of the work done, now waiting for Sonatype to verify the project creation issue at:
https://issues.sonatype.org/browse/OSSRH-2895

**Comment by kdowbecki** [comment]
SNAPSHOT artifacts were successfully deployed to Sonatype OSS repository, thus all the pom.xml comply to Sonatype OSS rules.
