### ISSUE TITLE
Problem setting attribute in Mule Step

### ISSUE THREAD

**Issue by zmalinowski** [bluesoft-rnd/aperte-workflow-core#51]
How to reproduce:
- Start Reservation process
- Fill in first step (search)
- Click continue

"Search" step is followed by "Validation" Mule Step and, after that, XOR evaluating "valid" attribute value (set by "Validation"). Usually evaluation throws an exception that attribute was not found. However, in retry problem never occurs.

**Comment by kdowbecki** [comment]
This error message may be misleading because it may appear when there was an internal error during MuleStep execution. Then the correct exception stack trace is printed in the logs, however the user gets this message. We need to improve error handling here.

**Comment by kdowbecki** [comment]
Fixed in #50. Closing.
