### ISSUE TITLE
Aperte Modeler with Tomcat 7.0.23 on port 8082

### ISSUE THREAD

**Issue by andresaznar** [bluesoft-rnd/aperte-workflow-core#70]
I'm trying to deploy Aperte Modeler on Tomcat 7.0.23 and Liferay 6.1. This tomcat is running with Liferay but in port 8082 (not 8080), and with Mysql.

Using http://localhost:8082/apertemodeler I access to the login page. Previously I changed the "configuration.properties" file on  "C:\Liferay\tomcat-7.0.23\webapps\apertemodeler\WEB-INF\classes" directory.

host = http://localhost:8082
fileSystemRootDirectory = 
aperteStepEditorUrl = /step_editor
aperteActionEditorUrl = /action_editor
aperteStepListUrl = /osgiex/steps?format=json
aperteOsgiPluginsDir = 
aperteButtonListUrl = /osgiex/buttons?format=json
jbpmGuiUrl = /aperteworkflow

After introduce the login and password I get a message: "The application could not be loaded. Please double check your internet connection and reload the page" and I cannot access to the application. 

With the complete bundle (tomcat 6 + liferay 6.0.x) on port 8080 the program runs without problems.

Do you know what I need to change in order to run the program on port 8082 with Tomcat 7?

**Comment by tlipski** [comment]
Hi, do you have aperteworkflow deployed there too? Because host setting
points to an address where /aperteworkflow context is located. It can be
different port/host but it has to point to aperteworkflow (not modeler)
On Feb 29, 2012 4:13 PM, "andresaznar" <
reply@reply.github.com>
wrote:

**Comment by tlipski** [comment]
If that does not help, do you mind providing a github gist with http headers log (e.g. from livehttpheaders for firefox plugin)

**Comment by tlipski** [comment]
oh, by aperteworkflow i mean aperteworkflow.war (single file or unpacked). The standalone archive can be copied from bundle/demo installation or from http://sourceforge.net/projects/aperteworkflow/files/AW1.0/aperteworkflow.war/download

And please take note, that when manually configuring Aperte Workflow/Modeler, you should create at least ${liferay.home}/modeler-repo directory.

**Comment by andresaznar** [comment]
Hi,

I use the war file and deploy it in the deploy directory of liferay. Once deployed I changed the configuration.properties file in the directory C:\Liferay\tomcat-7.0.23\webapps\apertemodeler\WEB-INF\classes as I explained. But the application does not work after the login page.

I copy the bundle demo and this bundle runs ok.  I copied the directory C:\Liferay\modeler-repo from bundle demo to my implementation on port 8082, but still have the same problem.

I think this is not a problem about port, because I access to the Login page at :8082\apertemodeler so something does not work...

In the Tomcat window, I get the message you can see in this screenshot

http://www.flickr.com/photos/81323669@N00/6941428043/

**Comment by tlipski** [comment]
Do you have aperteworkflow.war in webapps directory as well?
On Feb 29, 2012 5:47 PM, "andresaznar" <
reply@reply.github.com>
wrote:

**Comment by tlipski** [comment]
Oh, I see from a screenshot/logs that you do. So, we can do two things (regardless of each other). I will try to run app on port 8082 - but that works - for example https://demo.aperteworkflow.org/apertemodeler runs fine and tomcat is on port 9020.

One thing that may also require changing, as configuration.properties file is rendered from build.properties during bundle compilation are some entries in JavaScript. I will look into that.

**Comment by andresaznar** [comment]
I check the demo-build and my deployment of Aperte Modeler and there is no "build.properties" file in the directories.

One think I show is:

1.- When I try to access to http://localhost:8082/apertemodeler the login screen appears.
2.- This login screen is the C:\Liferay\tomcat-7.0.23\webapps\apertemodeler\login.html file
3.- After the login.html screen, with correct authentication, I suppose the application goes to C:\Liferay\tomcat-7.0.23\webapps\apertemodeler\index.html screen

And it seems that is index.html that cannot include the images, logos etc...

**Comment by tlipski** [comment]
Ok, I have done the following steps and everything works on other port (8086 in my case):
1. changed 

```
<Connector port="8080" protocol="HTTP/1.1" 
```

in conf/server.xml to 

```
<Connector port="8086" protocol="HTTP/1.1"
```
1. changed host parameter in webapps/apertemodeler/WEB-INF/classes/configuration.properties to:

```
host = http://localhost:8086
```
1. restarted tomcat

and everything seems to work OK, I can access process modeler, etc.

**Comment by tlipski** [comment]
The login screen from login.html should not appear - you should provide username/password by basic auth. I cannot help much without http request headers log, but one thing maybe that you can try is to clear browser cache?
Oh, and what browser are you using? Signavio Core components (sadly) does not support IE in any version

**Comment by andresaznar** [comment]
Ohh... it works on MS Internet Explorer !!! I checked and runs !!!... but not in Firefox...

With IE: http://www.flickr.com/photos/81323669@N00/6943323139/

With Firefox: http://www.flickr.com/photos/81323669@N00/6797207342/

**Comment by andresaznar** [comment]
Off course with IE no access to the process windows is allowed, as you explain..

**Comment by tlipski** [comment]
Right. Have you cleaned the cache on Firefox? Or tried Chrome?

**Comment by andresaznar** [comment]
Do you have an idea if there is any other add-on for liferay that causes incompatibility ? I have deployed the SHARE of Alfresco in the same tomcat, Aperte reports (for jasper reports integration) and Spreadsheet portlet from MyOffice24x7 ... The other portlets are the Liferay official (mail, knowledge database etc...).

**Comment by tlipski** [comment]
nah, that should't be an issue (aperte modeler uses only portal auth and invokes Aperte Workflow portlets directly)

**Comment by andresaznar** [comment]
It was the cache ... now it works ... Thanks very much.. Issue finished and archived.

**Comment by tlipski** [comment]
oh right, glad I could help :)

**Comment by MuhammedShakir** [comment]
Hi, 

I have deployed aperteworkflow 2.1 on Liferay 6.1.1. Except for userdata-widget everything got deployed successfully. Now when I deploy the apertemodeler on Liferay 6.1.1 I get the same error message that is reported here - i.e. after login half of image if Aperte Modeler is displayed and then a small dialog box says - Application Could not be loaded... please double check your internet connection. Do I have to change something in the explorer.js file.  The error console of the browser shows this

![screen shot 2013-08-04 at 8 57 30 pm](https://f.cloud.github.com/assets/1707820/907221/6c4eaee0-fd1a-11e2-8edf-4d3f96835ea5.png)
