### ISSUE TITLE
Aperte workflow: error in demo files

### ISSUE THREAD

**Issue by andresaznar** [bluesoft-rnd/aperte-workflow-core#71]
Hi Tomasz,

I have the implementation:

Tomcat 7.0.23
Liferay 6.1
Mysql 5.1.5

And I deployed the Aperte workflow WAR file (via Liferay home / deploy).

I created in tomcat context.xml the entry for the datasource container:

   
    <Resource auth="Container" driverClassName="com.mysql.jdbc.Driver" name="jdbc/aperte-workflow-ds" password="admin" type="javax.sql.DataSource" url="jdbc:mysql://localhost:3306/workflow" username="liferay"/>

And I created a DB called "workflow" with TOAD for MySQL, using "liferay" as user and "admin" as password.

In  the file C:\Liferay\tomcat-7.0.23\webapps\aperteworkflow\WEB-INF\web.xml there is the definition for the access to this container:

```
<resource-ref>
    <description>Aperte Workflow Datasource Reference</description>
    <res-ref-name>jdbc/aperte-workflow-ds</res-ref-name>
    <res-type>javax.sql.DataSource</res-type>
    <res-auth>Container</res-auth>
</resource-ref>
```

So this must be correct for the database connection and activity.

When I use the demo with the air tickets I can create a reservation, but if I try to cancel in the middle of the process, or after this, I go to make the task of finish the process, I get an error. You can look it in the pictures

http://www.flickr.com/photos/81323669@N00/6943332829/
http://www.flickr.com/photos/81323669@N00/6943332707/

I make the same with the bundle demo (tomcat 6, liferay 6.0.x, hqsql..) and no error found there. Is my configuration of the database correct with the changes I explained?

**Comment by andresaznar** [comment]
Sorry, this is the context xml configuration:

```
<Resource auth="Container" driverClassName="com.mysql.jdbc.Driver" name="jdbc/aperte-workflow-ds" password="admin" type="javax.sql.DataSource" url="jdbc:mysql://localhost:3306/workflow" username="liferay"/>
```

**Comment by tlipski** [comment]
Can you put stack trace from logs/catalina.out for this exception?

**Comment by andresaznar** [comment]
Seems something about database schema...

http://www.flickr.com/photos/81323669@N00/6797255282/

**Comment by tlipski** [comment]
Ok, I'll run the demo process on MySQL and see what happens.

**Comment by tlipski** [comment]
It seems to work O.K.
My datasource configuration in conf/context.xml:

```
    <Resource name="jdbc/aperte-workflow-ds" auth="Container" type="javax.sql.DataSource"
               maxActive="100" maxIdle="30" maxWait="10000"
               username="jbpm" password="jbpm" driverClassName="com.mysql.jdbc.Driver"
               url="jdbc:mysql://localhost:3306/a"/>
```

One difference is see is lack of maxActive maxIdle and maxWait attributes

**Comment by tlipski** [comment]
My conf/context.xml looks like this:

```
    <Resource name="jdbc/aperte-workflow-ds" auth="Container" type="javax.sql.DataSource"
               maxActive="100" maxIdle="30" maxWait="10000"
               username="jbpm" password="jbpm" driverClassName="com.mysql.jdbc.Driver"
               url="jdbc:mysql://localhost:3306/a"/>
```

**Comment by tlipski** [comment]
And it works OK on MySQL.

**Comment by andresaznar** [comment]
OK I will check with the params you send me... but it seems that there is a foreign key violation... maybe the creation of the database was not good and I need to reinstall everything... Let me check...

**Comment by tlipski** [comment]
But on clean schema it does not work - that's great, I'm on it :)

**Comment by tlipski** [comment]
seems like the issue is here https://issues.jboss.org/browse/JBPM-2333 and the fix is not use dialect autodetection.

**Comment by tlipski** [comment]
ok, I need to add custom DialectResolver, one sec

**Comment by andresaznar** [comment]
Ok... Which file I need to change ?

**Comment by andresaznar** [comment]
I think that I have a portlet that has this Hibernate dialog selection... I remember that I configure it before...

**Comment by tlipski** [comment]
you could force hibernate dialect in aperteworkflow/WEB-INF/lib/jbpm-context-1.0.jar!hibernate.cfg.xml
but I am working to enhance autodetection, since specifying dialect in hibernate.cfg.xml is not very portable.

**Comment by tlipski** [comment]
maybe it was liferay 6.1 configuration wizard - our hibernate configuration bases on datasource and autodetection

**Comment by tlipski** [comment]
i only need to find a place to inject my custom dialect detector class and hibernate.cfg.xml is not the right place to do that..

**Comment by andresaznar** [comment]
I think that was RCS Newletter, the portlet where you need to configure the hibernate dialog

**Comment by tlipski** [comment]
It's not MySQLInnoDBDialect, but MySQL5InnoDBDialect - for innodb, database schema creation fails.

**Comment by tlipski** [comment]
all right, it works(tm)

**Comment by tlipski** [comment]
fixed here: c7a5c1370610d7f911a3a819d4a1904a967957b4

i will upload aperteworkflow.war in mere minutes - see if this helps

**Comment by andresaznar** [comment]
So you will create a new release to download?

**Comment by tlipski** [comment]
release is maybe too much - but the updated .war is here https://github.com/downloads/bluesoft-rnd/aperte-workflow-core/aperteworkflow.war

**Comment by andresaznar** [comment]
So the reason is a bug in the jBPM core from JBoss, isn't it?

**Comment by tlipski** [comment]
Yes, but some may call it a configuration requirement :-)

With jBPM on Oracle it is even worse - you need to manually update schema.

Anyways, the Activiti support is ready in Aperte Workflow 1.1 branch (codes are there, but we haven't released a distribution yet) and jBPM5 support is pending, so more options regarding BPM engines will be available pretty soon.

**Comment by tlipski** [comment]
The portlet name has changed, so you have to re-add the portlet to the portal page.

**Comment by andresaznar** [comment]
Configuration requirement... yes, I know... 

BPM is far away from the past, when you need to program sockets with Staffware (before TIBCO buys it) or with Fujitsu Teamware. Yes, I'm a dinosaur...

Ok, I will check the new porlet names and add it. I use the private pages of the admin user to make this tries...

**Comment by tlipski** [comment]
ok, let me know if everything works OK

**Comment by andresaznar** [comment]
After cleaning the cache, deploy the new war file... PROCESS END... It runs !!!

**Comment by tlipski** [comment]
glad to hear it :)

**Comment by tlipski** [comment]
if you have any feature requests/insights or further bugs - just let us know

**Comment by andresaznar** [comment]
I will start now with the tutorial in order to create my own processes... You will have news...
