### ISSUE TITLE
Access Postgres data in aperte

### ISSUE THREAD

**Issue by sivaranjani** [bluesoft-rnd/aperte-workflow-core#77]
i m new to aperte..i want to know how to access the data from postgres sql to workflow..for ex in flight reservation process is there..In osgi plugin folder if we zip tat jar file means only one xml+manifest folder is there..if i create a new process means and deploy it means manifest+tat process folder is there..tat folder contains 3 xml files..

**Comment by tlipski** [comment]
sivaranjani, it would be best for you to acknowledge yourself with the documentation available in our wiki - https://github.com/bluesoft-rnd/aperte-workflow-core/wiki

If you need to access postgresql external database, everything depends on the specifics of the integration:
- you can access the datasource using Mule client and mule service - for example from Vaadin Widget rending UI
- you can also access postgresql simply using JDBC - from any part of the application

Also, Aperte Workflow can run on PostgreSQL itself - just configure appropriate datasource following Quick Start Guide from the wiki: https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Quick-start-guide

**Comment by sivaranjani** [comment]
Thank you..
As u said i created the db coding in mule using groovy..i cant able to create jar file similar to mule-flightsearch-sample.jar in flight reservation example... can u tell the steps how to create jar file for my own process..

**Comment by tlipski** [comment]
You can just use maven to do that, just check out the https://github.com/bluesoft-rnd/aperte-workflow-core/blob/master/samples/mule-flightsearch-sample/pom.xml as an example. For simple mule step you can skip using maven osgi plugin and just use regular maven jar packaging (just remember about including META-INF/MANIFEST.MF)

**Comment by sivaranjani** [comment]
how to create that in maven..can u please tell the steps to create that file as jar in maven....
