### ISSUE TITLE
Aperte with JBoss

### ISSUE THREAD

**Issue by ghost** [bluesoft-rnd/aperte-workflow-core#78]
Hi all,

I'm looking for aperte-bundlewith-jboss.....

If it is there, where can I download

**Comment by tlipski** [comment]
Hi,

JBoss bundle is not available at this moment, but you can easily deploy Aperte Workflow to JBoss using the Quick Start Guide (section Standalone WAR archive):  https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Quick-start-guide
