### ISSUE TITLE
Configuring Aperte process with external database

### ISSUE THREAD

**Issue by ghost** [bluesoft-rnd/aperte-workflow-core#79]
Hi all,

I'm using Aperte 1.0.

How do I configure Aperte with an external database.

Thanks in advance.....
Harish

**Comment by tlipski** [comment]
Hi,

Please review the Quick start guide document: https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Quick-start-guide on how to configure Aperte Workflow to run using database other than embedded HSQL.

Also, you might want to check for https://github.com/bluesoft-rnd/aperte-workflow-core/issues/77 - it provides other ways to access external databases.
