### ISSUE TITLE
source code for search using lucene search syntax

### ISSUE THREAD

**Issue by chandrakala** [bluesoft-rnd/aperte-workflow-core#81]
hi,i m new to aperte workflow.can i get the source code for search using lucene search syntax

**Comment by tlipski** [comment]
The sample implementation (I'm not totally happy with it) is in https://github.com/bluesoft-rnd/aperte-workflow-core/blob/master/core/integration/src/main/java/pl/net/bluesoft/rnd/processtool/plugins/ProcessToolRegistryImpl.java and related classes.

For lucene query syntax, there is a pretty good explaination on the Lucene project website: http://lucene.apache.org/core/old_versioned_docs/versions/3_5_0/queryparsersyntax.html
