### ISSUE TITLE
Adding Own Widgets

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#82]
I'm unable to add my own Vaadin(like Tree,Calendar)widgets to AperteStepEditor.Please suggest me how to add

**Comment by tlipski** [comment]
The best way to start would be to aknowledge yourself with https://github.com/bluesoft-rnd/aperte-workflow-core/issues/80 - I've put a simple description where to start. Anyway, these questions are really good, so we will set up more detailed tutorials in the following days.

**Comment by murthy516** [comment]
But,there is a topic called CreatingSampleWidgets in github of Aperte.If I click that topic,it is generating message as "You donot have Permission to Update this wiki".I need to look at that topic.How can I?Please suggest me
