### ISSUE TITLE
Aperte with Drools 

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#84]
Hi,

In my Aperte flow i taken a TaskType as DroosStep in that ruleUrl what i have suppose to write please suggest me
if i give the my drl file name it is giving IllegalArguementException & mulformed exception

If any example on Aperte with Drools please share..

Regards,
Veera

**Comment by tlipski** [comment]
Hi, the answer is in #92, I also see that you've found a way to work with Drools by yourself - sorry for the delay in closing issues.
