### ISSUE TITLE
sample program for how to make field name as searchable

### ISSUE THREAD

**Issue by chandrakala** [bluesoft-rnd/aperte-workflow-core#85]
Thank u for the quick response.Defaultly aperte taking process instance name as searchable.(i.e in search box if we are giving any process instance name then it is doing wildcard,fuzzy,..etc searching ).similarly i have to do for some fields(attributes) which are part of the process instances. can you plz  give an example program for how to make some field as searchable.

**Comment by tlipski** [comment]
Aperte Workflow provides its own mechanisms to store process data - using Hibernate. The main object is of class ProcessInstance and it can contain a set of attributes using ProcessInstanceAttribute.

Attributes can be customized by extending the base class, so you can provide your own structures for process data. For simple cases, such as key-value process attributes, there i a default implementation - ProcessInstanceSimpleAttribute.

Such attribute is used for example as a default for ProcessDataWidget - you can just supply
bind attribute to a variable name, and ProcessDataWidget will create appropriate  attributes with such names for further reference.

For example, in flight process, in first step, for ProcessDataWidget, we have such entry:

```
  <date fullSize="false" undefinedSize="false" bind="departureDate" readonly="false" caption="Departure date" format="dd-MM-yyyy" not-before="current" showMinutes="false" required="true"/>
```

And later on, in Groovy script processing flight search dummy logic we can access this attribute:

def dDate = payload.getSimpleAttributeValue("departureDate");

Also, process attributes can be mapped to BPM variables by implementing BpmVariable interface and be used to search for processes by implementing Searchable interface.

If you need to extend process attributes with some custom structures, it is best to review one of the example plugins, such as userdata-widget: https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/userdata-widget
