### ISSUE TITLE
Want to access 2 process from one single process

### ISSUE THREAD

**Issue by sivaranjani** [bluesoft-rnd/aperte-workflow-core#87]
Thank you in advance..

In my 1st process 2 radio button is there..if i click one button means it should call 2nd process and if i click another button means it  should call 3rd process...How ill do tis..Suggest me...

**Comment by tlipski** [comment]
It should be possible by providing some shared space for processes:
- custom model (e.g. ProcessCommunicationBuffer) or 
- some kind of OSGi service (may cause problems in clustered environment, so careful implementation is necessary) or
- (worst way) some kind of shared memory 

You can also create a custom plugin subscribing for events API (see https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/bpm-notifications), which would be able to catch an event appearing from one process and to access execution of another process (just like https://github.com/bluesoft-rnd/aperte-workflow-core/tree/master/plugins/email-capture does). In fact, you could even configure these two plugins to work toghether to provide email-based process synchronization.
