### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by harinatha** [bluesoft-rnd/aperte-workflow-core#89]
how can i do pagination in aperte please suggest me

**Comment by tlipski** [comment]
It really depends what do you need to paginate. 

Task lists are paginated by default (maybe not always in an optimized way), same for search results (although Lucene does not provide pagination means - but still is very fast, so not an issue at this moment).

Pagination of data on custom controls made with Vaadin components can be achieved in several ways, from using appropriate container to implementing custom pagination logic directly in your code.
