### ISSUE TITLE
How to create Dependent combo box?

### ISSUE THREAD

**Issue by sivaranjani** [bluesoft-rnd/aperte-workflow-core#90]
Hi,
      I want to create a dependent combo box. When one combo box value is selected, based on that selection the second combo box value is generated. Any one please help me...

**Comment by tlipski** [comment]
At this moment, you can achieve that by creating custom Vaadin Widget. There you can put all the logic that is required (you are also welcome to contribute it back to the project). 

Another approach would be to use scripting feature incoming in 1.1 or to wait for 1.3 which should provide multi-level dictionaries to ProcessDataWidget.
